GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/media/sasank/LinuxStorage/Dropbox (UFL)/LitJTML/scripts/train.py", line 72, in <module>
    trainer.fit(model, data_module)
  File "/home/sasank/miniconda3/envs/sasank-jtml-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/sasank/miniconda3/envs/sasank-jtml-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/sasank/miniconda3/envs/sasank-jtml-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/sasank/miniconda3/envs/sasank-jtml-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1105, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/sasank/miniconda3/envs/sasank-jtml-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1447, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/home/sasank/miniconda3/envs/sasank-jtml-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1569, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/media/sasank/LinuxStorage/Dropbox (UFL)/LitJTML/scripts/lit_datamodule.py", line 58, in setup
    self.training_set = LitJTMLDataset(dataset=self.train_set, img_dir=self.img_dir)
  File "/media/sasank/LinuxStorage/Dropbox (UFL)/LitJTML/scripts/lit_JTMLDataset.py", line 38, in __init__
    raise Exception('Error, cannot find file: ' + self.images[idx])
Exception: Error, cannot find file: grid_Calib file test_000000000381.tif